### ISSUE TITLE
G35 Lights in ESPHome

### ISSUE THREAD

**Issue by jlboygenius** [openfirmware/esphome_files#1]
I guess GitHub doesn't allow direct messages, so this is my lame way to send you a message. :)

I was looking into getting GE color effects lights to work in ESPHome, and google led me to your blog. You might be the only other person on the planet who has these old lights and thought about integrating them into Home Assistant. 

Anyway, I did make them work and I thought you might find it useful:
https://github.com/jlboygenius/ESPHome_GEColorEffects

I've only got them working as a Light right now, so Home Assistant sees the strip as one light bulb. I made some switches that turn on custom patterns. I'd like to be able to get them to work as an "Addressable Light", which would allow ESPHome to see it as an LED Light strip, but I haven't gotten that far yet.

It does require removing the original controller and replacing it with an ESP32 (or any ESPHome device ).

**Comment by openfirmware** [comment]
Hey that's great! I haven't had time to work on my lights project lately, but I think there is still a lot of neat things these lights can do. I was able to load the [Arduino G35 lights sample code](https://github.com/chsnow/g35-arduino) onto an ESP8266, so hopefully the features can be combined with ESPHome as a custom component. Thanks!
